apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-forwarder
subsets:
  - addresses:
      - ip: {{ required "target.ip" .Values.target.ip }}
    ports:
      - port: {{ required ".target.port" .Values.target.port }}
        protocol: TCP
