apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-forwarder
  {{- template "ingress.annotations" . }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      secretName: {{ .Values.host | replace "*" "wildcard" | replace "." "-" }}-tls
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-forwarder
                port:
                {{- $service := .Values.service }}
                  number: {{ $service.port }}